version: '2'
services:
  redis:
    image: redis:7-bullseye
    ports:
      - '6739:6379'
    command: redis-server --save "" --appendonly no
  critical-css:
    build: .
    command: npm start
    ports:
      - '5001:5001'
    depends_on:
      - redis
    volumes:
      - ./:/app_home:delegated      
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0